name: Cherry-Pick Hardcoded Commits

on:
  workflow_dispatch: 

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          ref: A8XX-NEW          
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch donor repo and cherry-pick
        run: |
          # Подключаем репозиторий 
          git remote add donor https://github.com/DiskDVD/A8XX-Y
          git fetch donor A8XX

          # Запуск cherry-pick для ваших коммитов
          echo "Переносим коммиты..."
          git cherry-pick 97802f1 93c462d ef47234 8d7973a 63e0ded e68a654 20c01b2 dcbb41b d96a891 d854a45 2a0181b 49c3da3 ce0f777 1d163f6 bc16322 0057828 1ebd39a 6499422 02e081 6d3c67f b231482 ccd24cd 41f6148 b3ad1b2 81c8610   

      - name: Push changes
        run: git push origin HEAD:A8XX-NEW
